#!/bin/sh

PATH=/usr/local/bin:$PATH

DUMP=/root/db
umask 0
rm -rf $DUMP && mkdir $DUMP

for db in `mysql --skip-column-names -Be 'show databases' | grep -v _schema | grep -v mysql`
do
  echo "db: $db"
  DBDIR=$DUMP/$db
  mkdir $DBDIR
  chmod o+wx $DBDIR
  mysqldump -d --skip-triggers $db > $DBDIR/$db.schema_NT_NR.ddl
  mysqldump -R -d $db > $DBDIR/$db.schema_full.ddl
#  for table in `mysql $db --skip-column-names -Be 'show full tables where Table_Type <> "VIEW"' | perl -lpe 's/\t.*//'`
#  do
#	(mysqldump -C --skip-triggers $db $table > $DBDIR/$table.sql &&
#	p7zip $DBDIR/$table.sql > /dev/null) &
#  done

  mysqldump -R $db |gzip > $DUMP/$db.sql.gz
done

