#!/bin/sh

# single-file backup mysql to AWS S3

service tomcat7 stop # we need the RAM

export HOME=/root
TARG=$1
PATH=/usr/local/bin:$PATH

if [ "$TARG" = "" ]
then
	echo "Usage: $0 [target]"
	exit 1
fi

echo "Backup started @ $(date)"

mysqldump -A -R > full-backup.sql

echo "Compression started @ $(date)"

(lrzip full-backup.sql; echo "lrzip done @ $(date)") &
(7z a full-backup.sql.7z full-backup.sql; echo "7zip done @ $(date)") &

wait

echo "S3 Copy started @ $(date)"

aws s3 cp full-backup.sql.* $TARG/

echo "Backup ended @ $(date)"
