#!/bin/sh -x
SWAPFILE=/mnt/swapfile
dd if=/dev/zero of=$SWAPFILE bs=1024 count=1024000
chown root:root $SWAPFILE
chmod 600 $SWAPFILE
mkswap $SWAPFILE
swapon $SWAPFILE
echo $SWAPFILE none swap sw 0 0 >> /etc/fstab
swapon -s
