#!/bin/sh -x
dd if=/dev/zero of=/swapfile bs=1024 count=4096000
chown root:root /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo /swapfile none swap sw 0 0 >> /etc/fstab
swapon -s
